# Generated by Django 5.0.2 on 2024-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='images/')),
                ('icon_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='OpenAI_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=300)),
                ('model_name', models.CharField(max_length=300)),
                ('error_status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=250)),
                ('website_url', models.URLField()),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('application_password', models.CharField(max_length=250)),
            ],
        ),
    ]
