# Generated by Django 5.0.2 on 2024-03-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website_list',
            name='user',
        ),
    ]
