# Generated by Django 5.0.3 on 2024-03-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_remove_website_list_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
