# Generated by Django 5.0.2 on 2024-03-03 16:19

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generated_news_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('content', tinymce.models.HTMLField()),
                ('logs', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('website_url', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('app_pass', models.CharField(blank=True, max_length=250, null=True)),
                ('post_status', models.CharField(blank=True, max_length=50, null=True)),
                ('category_name', models.CharField(blank=True, max_length=250, null=True)),
                ('feature_img_status', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_time', models.DateTimeField(auto_now=True)),
                ('schedule_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='news_generate_Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='title')),
                ('news_body', models.TextField(default='Content body prompt')),
                ('image_generation', models.TextField(default='Img Command')),
            ],
        ),
    ]
