# Generated by Django 5.0.2 on 2024-03-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generated_news_list',
            name='user',
        ),
    ]
