# Generated by Django 5.0.2 on 2024-03-04 09:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0004_alter_news_generate_command_image_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_news_list',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
